sudo: false
language: ruby
before_install: gem install bundler -v 1.14.3
script:
  - bundle exec rspec spec/
matrix:
  include:
    - rvm: 2.2.2
    - rvm: 2.3.0
    - rvm: 2.4.0
after_script: bundle exec codeclimate-test-reporter
